"""cash register

Revision ID: 857ce7c2da52
Revises: d54ac52081bf
Create Date: 2026-05-26 13:47:35.046071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '857ce7c2da52'
down_revision: Union[str, Sequence[str], None] = 'd54ac52081bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
       # ### end Alembic commands ###
