"""add matricula employee

Revision ID: ae1e4be27b90
Revises: 009264303baf
Create Date: 2026-05-28 07:10:39.647966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae1e4be27b90'
down_revision: Union[str, Sequence[str], None] = '009264303baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_flow')
    op.drop_table('cash_register')
    op.drop_table('employees')
    op.drop_constraint(op.f('products_codigo_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_codigo'), 'products', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_codigo'), table_name='products')
    op.create_unique_constraint(op.f('products_codigo_key'), 'products', ['codigo'], postgresql_nulls_not_distinct=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_admissao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey')),
    sa.UniqueConstraint('cpf', name=op.f('employees_cpf_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name=op.f('employees_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cash_register',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fundo_caixa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('saldo_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aberto_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fechado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['employees.id'], name=op.f('cash_register_funcionario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_register_pkey'))
    )
    op.create_table('cash_flow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_flow_pkey'))
    )
    # ### end Alembic commands ###
