"""add parcelas sale

Revision ID: e9b0045c4b06
Revises: 4bbdc7f00121
Create Date: 2026-06-07 12:26:58.464299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b0045c4b06'
down_revision: Union[str, Sequence[str], None] = '4bbdc7f00121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column(
        'sales',
        sa.Column(
            'parcelas',
            sa.Integer(),
            nullable=True
        )
    )

    op.add_column(
        'sales',
        sa.Column(
            'valor_parcela',
            sa.Float(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column(
        'sales',
        'valor_parcela'
    )

    op.drop_column(
        'sales',
        'parcelas'
    )
    # ### end Alembic commands ###
